
spring:
  datasource:
    url: "jdbc:h2:~/local_db"
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update

logging.level:
  org: info
  at.idk: info
  com.zaxxer.hikari: info